
title: Nina Nusbaumer
logo: /assets/img/NN.png
description: >
  1st-year PhD student <br>
  ğŸ‘©ğŸ»â€ğŸ“ UniversitÃ© Paris CitÃ© <br>
  ğŸ“Currently visiting COLT in Barcelona

show_downloads: false
theme: jekyll-theme-minimal
